### ISSUE TITLE
The demo page only works on chrome

### ISSUE THREAD

**Issue by Sharelive** [mediahub-bg/clappr-bandwidth-analyzer#1]
https://mediahub-bg.github.io/clappr_bandwidth_analyzer_demo.html

Doesn't work on Firefox or Explorer/Edge, works fine on Chrome though.

Cheers!

**Comment by stojnovsky** [comment]
Hi Sharelive,
In Compatibility point in review for plugin (README.md) I already write:

This working only if video is playing on HTML5 Video Tag and browser support following properties on HTML5 Video Tag:

webkitVideoDecodedByteCount
webkitDroppedFrameCount
webkitDecodedFrameCount

-
as use see the prefix of functions is "webkit" - so in this case that mean only Chrome and Chromium based browsers. Other browsers don' have functionality to decodedBytes so easy. Maybe in next version I will calculate this information directly from blob.

In my case we use the plugin to can easy debug the size of video (400kbits or 3mbits). Is not for client side - so it easy to say of our support team - please use Chrome :)

Sorry for the big delay of my answer.
